In [ ]:
#Mathematics for Data Science

## Mathematics for Data Science

NumPy provides us with a huge collection of high-level functions for
  multi-dimensional arrays

### .zeros()

- To create a NumPy array prefilled with zeros, we can use the `.zeros()`
  built-in NumPy functions
- To convert a list prefiled with zeros into a integer list, we use the
  `astype()` function

In [2]:
import numpy as np

zerosArray = np.zeros(10) # create an array with 10 zeros (float)
print(zerosArray)
print(type(zerosArray))

zArrConverted = zerosArray.astype(int)
print(zArrConverted)
print(type(zArrConverted))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


### .ones()

- To create a NumPy array prefilled with ones, we can use the `.ones()`
  built-in NumPy functions
- To convert a list prefiled with zeros into a integer list, we use the
  `astype()` function

In [3]:
import numpy as np

onesArray = np.ones(10) # create an array with 10 ones (float)
print(onesArray)
print(type(onesArray))

oArrConverted = onesArray.astype(int)
print(oArrConverted)
print(type(oArrConverted))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>


### .full()

- To create a NumPy array prefilled with some specific number, we can use the `.full()`
  built-in NumPy functions:
  - 1st argument in the full() function is the size of the array
  - 2nd argument is the value the we want our list to be prefilled with

In [6]:
import numpy as np

fullArray = np.full(10, 7) # create an array with 10 sevens
print(fullArray)
print(type(fullArray))

fullArray2 = np.full(10, 7.9) # create an array with 10 sevens dot nine (floats)
print(fullArray2)
print(type(fullArray2))

[7 7 7 7 7 7 7 7 7 7]
<class 'numpy.ndarray'>
[7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9]
<class 'numpy.ndarray'>


## Scalar Operations

### Addition

- We can add a scalar to a NumPy array simply by using the `+` operator
- The scalar quantity is added to each of the elements of the array
- Note that adding a scalar to a Python list will result in an error

In [7]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix + 2)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [8]:
pythonList = [[1, 2, 3], [4, 5, 6]]
print(pythonList)

print(pythonList + 2)

[[1, 2, 3], [4, 5, 6]]


TypeError: can only concatenate list (not "int") to list

### Subtraction

- We can subtract a scalar to a NumPy array simply by using the `-` operator
- The scalar quantity is subtracted from each of the elements of the array
- Note that subtracting a scalar to a Python list will result in an error

In [9]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix - 2)

[[1 2 3]
 [4 5 6]]
[[-1  0  1]
 [ 2  3  4]]


In [10]:
pythonList = [[1, 2, 3], [4, 5, 6]]
print(pythonList)

print(pythonList - 2)

[[1, 2, 3], [4, 5, 6]]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

### Multiplication

- We can multiply a scalar to a NumPy array simply by using the `*` operator
- The scalar quantity is multiplied from each of the elements of the array
- Note that multiplying a scalar to a Python list will result in list concatenation

In [11]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix * 2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [12]:
pythonList = [[1, 2, 3], [4, 5, 6]]
print(pythonList)

print(pythonList * 2)

[[1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


### Division

- We can divide a scalar to a NumPy array simply by using the `/` operator for a
  float division and `//` for an int division
- Each of the elements of the array is divided by the scalar
- Note that dividing a Python list by a scalar will result in an error

In [13]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix / 2)
print(matrix // 2)

[[1 2 3]
 [4 5 6]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0 1 1]
 [2 2 3]]


In [14]:
pythonList = [[1, 2, 3], [4, 5, 6]]
print(pythonList)

print(pythonList / 2)

[[1, 2, 3], [4, 5, 6]]


TypeError: unsupported operand type(s) for /: 'list' and 'int'

### Power

- We can raise each element of a NumPy array to a power simply by using the `**` operator
- Note that raising the elements of a Python list using `**` will result in an error

In [15]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix ** 2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [16]:
pythonList = [[1, 2, 3], [4, 5, 6]]
print(pythonList)

print(pythonList ** 2)

[[1, 2, 3], [4, 5, 6]]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Transpose

- We can take the transpose of a NumPy array by putting `.T` at the end of the array
- Note that taking the transpose of a Python list will result in an error

In [17]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print(matrix.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
pythonList = [[1, 2, 3], [4, 5, 6]]
print(pythonList)

print(pythonList.T)

[[1, 2, 3], [4, 5, 6]]


AttributeError: 'list' object has no attribute 'T'