In [ ]:
#Mathematics for Data Science

## Mathematics for Data Science

NumPy provides us with a huge collection of high-level functions for
  multi-dimensional arrays

### .zeros()

- To create a NumPy array prefilled with zeros, we can use the `.zeros()`
  built-in NumPy functions
- To convert a list prefiled with zeros into a integer list, we use the
  `astype()` function

In [2]:
import numpy as np

zerosArray = np.zeros(10) # create an array with 10 zeros (float)
print(zerosArray)
print(type(zerosArray))

zArrConverted = zerosArray.astype(int)
print(zArrConverted)
print(type(zArrConverted))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0]
<class 'numpy.ndarray'>


### .ones()

- To create a NumPy array prefilled with ones, we can use the `.ones()`
  built-in NumPy functions
- To convert a list prefiled with zeros into a integer list, we use the
  `astype()` function

In [3]:
import numpy as np

onesArray = np.ones(10) # create an array with 10 ones (float)
print(onesArray)
print(type(onesArray))

oArrConverted = onesArray.astype(int)
print(oArrConverted)
print(type(oArrConverted))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>


### .full()

- To create a NumPy array prefilled with some specific number, we can use the `.full()`
  built-in NumPy functions:
  - 1st argument in the full() function is the size of the array
  - 2nd argument is the value the we want our list to be prefilled with

In [6]:
import numpy as np

fullArray = np.full(10, 7) # create an array with 10 sevens
print(fullArray)
print(type(fullArray))

fullArray2 = np.full(10, 7.9) # create an array with 10 sevens dot nine (floats)
print(fullArray2)
print(type(fullArray2))

[7 7 7 7 7 7 7 7 7 7]
<class 'numpy.ndarray'>
[7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9 7.9]
<class 'numpy.ndarray'>
