## NumPy Arrays

- Are multidimensional data structures, designed to handle large data sets easily
- A NumPy array is called **ndarray**
- Allows find the number of dimensions of a NumPy array using `.ndim`

## NumPy Arrays vs Python Lists

- NumPy arrays provide more built-in functionality as compared to Python Lists
- NumPy arrays make working with huge multidimensional data sets much easier
  with fewer syntax
- NumPy arrays are also more efficient than Python lists in terms of memory
  consumption and speed

## 1-D NumPy Arrays

- where each element of the outermost array is a 0-D array (scalar)
- we can create a NumPy array using the `array()` function in the NumPy library
- we can create a NumPy array using either Python lists or tuples
- To create a 1-D NumPy array, we provide a 1-D Python list or tuple to the
  `array()` function

In [4]:
import numpy as np

oneDArray = np.array([1, 2, 3, 4, 5])
print(oneDArray)
print(type(oneDArray))
print(oneDArray.ndim)

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray)
print(type(twoDArray))
print(twoDArray.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


## 3-D NumPy arrays

- where each element of the outmost array is a 2-D array
- To create a 3-D NumPy array, we provide a 3-D Python list or tuple to the
  `array()` function

In [10]:
import numpy as np

trheeDArray = np.array([
    [[1, 2, 3], [-1, -2, -3]], # 1st 2-D list
    [[4, 5, 6], [-4, -5, -6]]  # 2nd 2-D list
])
print(trheeDArray)
print(type(trheeDArray))
print(trheeDArray.ndim)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
<class 'numpy.ndarray'>
3


## Indexing NumPy Arrays

### 1-D NumPy arrays

- Indexing a 1-D NumPy array is the same as indexing a 1-D Python list
- Provide the index of the element inside the square brackets to get that element


In [11]:
import numpy as np

oneDArray = np.array([1, 2, 3, 4, 5])
print(oneDArray[2])

3


### 2-D NumPy arrays

In [14]:
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray[1])
print(twoDArray[1][2])
print(twoDArray[1, 2])

[4 5 6]
6
6


3-D NumPy Arrays

- To index a 3-D NumPy array, we provide 3 values inside the square brackets
  - 1st is the index of the inner 2-D array in the first dimension
  - 2nd is the index of the inner 1-D array in the second dimension
  - 3rd is the index of the element in the third dimension

In [22]:
import numpy as np

trheeDArray = np.array([
    [[1, 2, 3], [-1, -2, -3]], # 1st 2-D list
    [[4, 5, 6], [-4, -5, -6]]  # 2nd 2-D list
])

print(trheeDArray[1])
print(trheeDArray[1][0])
print(trheeDArray[1, 0])
print(trheeDArray[1][0][2])
print(trheeDArray[1, 0, 2])

[[ 4  5  6]
 [-4 -5 -6]]
[4 5 6]
[4 5 6]
6
6


## Array Shape

NumPy arrays have a `shape` attribute which returns a tuple:
- 1st value gives the number of dimensions in the array
- 2nd value gives the number of elements in each dimension

In [23]:
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray.shape)

(2, 3)


## Iterating over NumPy arrays

### 1-D NumPy arrays

- Iterate over a 1-D array just the way we do in a 1-D Python list


In [24]:
import numpy as np

oneDArray = np.array([1, 2, 3, 4, 5])

for i in oneDArray:
    print(i)

1
2
3
4
5


### 2-D NumPy arrays

Use a nested `For` loop to iterate over a 2-D NumPy array:
- The outer For loop iterates over the outer array
- The inner For loop iterates over the inner array

In [27]:
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])

for i in twoDArray:
    for j in i:
        print(j)

1
2
3
4
5
6


### 3-D NumPy arrays

Use a nested `For` loop to iterate over a 3-D NumPy array:
- The outer For loop iterates over the array in the first dimension
- The middle For loop iterates over the array in the second dimension
- The inner For loop iterates over the array in the third dimension

In [29]:
import numpy as np

trheeDArray = np.array([
    [[1, 2, 3], [-1, -2, -3]], # 1st 2-D list
    [[4, 5, 6], [-4, -5, -6]]  # 2nd 2-D list
])

for i in trheeDArray:
    for j in i:
        for k in j:
            print(k)

for matrix in trheeDArray:
    for row in matrix:
        for scalar in row:
            print(scalar)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6
1
2
3
-1
-2
-3
4
5
6
-4
-5
-6
