## NumPy Arrays

- Are multidimensional data structures, designed to handle large data sets easily
- A NumPy array is called **ndarray**
- Allows find the number of dimensions of a NumPy array using `.ndim`

## NumPy Arrays vs Python Lists

- NumPy arrays provide more built-in functionality as compared to Python Lists
- NumPy arrays make working with huge multidimensional data sets much easier
  with fewer syntax
- NumPy arrays are also more efficient than Python lists in terms of memory
  consumption and speed

## 1-D NumPy Arrays

- where each element of the outermost array is a 0-D array (scalar)
- we can create a NumPy array using the `array()` function in the NumPy library
- we can create a NumPy array using either Python lists or tuples
- To create a 1-D NumPy array, we provide a 1-D Python list or tuple to the
  `array()` function

In [4]:
import numpy as np

oneDArray = np.array([1, 2, 3, 4, 5])
print(oneDArray)
print(type(oneDArray))
print(oneDArray.ndim)

twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray)
print(type(twoDArray))
print(twoDArray.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


## 3-D NumPy arrays

- where each element of the outmost array is a 2-D array
- To create a 3-D NumPy array, we provide a 3-D Python list or tuple to the
  `array()` function

In [10]:
import numpy as np

trheeDArray = np.array([
    [[1, 2, 3], [-1, -2, -3]], # 1st 2-D list
    [[4, 5, 6], [-4, -5, -6]]  # 2nd 2-D list
])
print(trheeDArray)
print(type(trheeDArray))
print(trheeDArray.ndim)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
<class 'numpy.ndarray'>
3
